### ISSUE TITLE
missing items

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona-docs#1]
- [ ] general introduction
  - [x] what is Dodona
  - [ ] short instruction video that outlines Dodona
- [x] user information: add requirement of having a user account, with link to page describing how to obtain an account (we need to draft our policy on who can get an account on Dodona)
- [x] teacher information: add requirement of having the role "staff" before you can register repositories or make new courses (we need to draft our policy on who can get the "staff" role)
- [ ] more detailed description needed on adding a repository (order needs to be checked)
  - [x] create github repository
  - [x] give github account of Dodona access to github repository
  - [x] register github repository on Dodona
  - [x] configure web hook
  - [x] refresh entire repository
  - [ ] FAQ
    - [x] should I make my repository public or private?
    - [ ] what should I do when moving a repository to another location?

**Comment by bmesuere** [comment]
Documentation moved to https://github.com/dodona-edu/dodona-edu.github.io
