### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by mdnert** [dodona-edu/dodona-docs#12]
Ik wil een oefening aanpassen, maar er is iets veranderd aan het werken met de hook.
Ik volgde de uitleg op https://developer.github.com/webhooks/creating/#setting-up-a-webhook maar mijn wijzigingen worden niet doorgevoerd.
Het gaat over de cursus https://dodona.ugent.be/nl/repositories/10/
Wie kan helpen?

**Comment by bmesuere** [comment]
Er is voor zover wij weten niets veranderd aan de webhook, dus alles zou nog steeds moeten werken als ze ooit correct was ingesteld. Ik heb geen beheerdersrechten op de repository die je linkte, dus ik kan niet zien of alles daar correct staat. Ik zie wel dat de laatste commit op de repository die aan de gelinkte cursus hangt (https://github.ugent.be/iii/dodonainformatica1) dateert van 2018. Er zijn dus geen recente aanpassingen die de webhook kunnen getriggerd hebben.

Ben je zeker dat je je (lokale?) aanpassingen gepusht hebt naar github en dat je in de juiste repository aan het werken bent?

**Comment by mdnert** [comment]
Bedankt voor het snelle antwoord - ik zat inderdaad in de verkeerde repository.
