### ISSUE TITLE
naming convention for screenshots (proposal)

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona-docs#3]
Format for naming screenshot files:

```
[<platform state>.][<user state>.]<object>[_<state>][.[<action>][_state] ...][.<subobject>[_<state>][.[<action>][_state] ...] ...].png
```

***examples***

```
nl.staff.courses.create_start.png
nl.course_admin.course_new.update.registration_link.copy.png
nl.course_user.course_open.register_start.png
```

### object states

- platform (languages)
  - *no object*: any language (used for language-agnostic screenshots, e.g. icons)
  - `nl`: Dutch
  - `en`: English
- user (roles, should all correspond to different users)
  - *no object*: signed-out user
  - `user`: signed-in user (not enrolled for any course)
  - `course_user`: user enrolled for demo course, but no admin for this course
  - `course_admin`: admin for demo course
  - `staff`: object creator for platform; admin for demo course
  - `zeus`: admin for platform; admin for demo course
- courses
  - *no state*: course overview (all courses)
  - `home`: home page (courses of signed-in user)
- course
  - *no state*: demo course without any specific characteristics (visibility:visible; registration procedure:open; managed by zeus, staff and course_admin)
  - `visible`: visible course (managed by course_admin)
  - `hidden`: hidden course (managed by course_admin)
  - `open`: open course (managed by course_admin)
  - `closed`: closed course (managed by course_admin)
  - `moderated`: moderated course (managed by course_admin)
  - `new`: Dodona manual: created and managed by staff, managed by course_admin (different users)
  - `unmanaged`: not managed by course admin
- series (plural)
  - *no state*: all series (learning path)
- series (singular)
  - `new`: Dodona manual: created by staff
  - `open`: open series (in course)
  - `hidden`: hidden series (in course)
  - `closed`: closed series (in course)

### common actions

- `create`: create a new object
- *no action*: read (view) an object (navigate to object and see how it is displayed)
- `update`: update an object
- `delete`: delete an object

### action states

- *no state*: action is ongoing
- `start`: action is about to be started
- `cancel`: action is about to be cancelled
- `confirm`: action is about to be confirmed
- `done`: action has been performed

**Comment by pdawyndt** [comment]
@evertvp Here's a proposed naming convention for the screenshots in the manual. I've gone through the screenshots in the course management chapter and applied the proposal to all of them. Could you review both the naming convention and its application in that chapter to see if this looks OK to you.

**Comment by ghost** [comment]
This seems like a good system. On first thought I can only think of one thing that I would change: I would do away with the implicit *no state*/*no action* parts and make them explicit. E.g. signedout/all/read/etc...

**Comment by bmesuere** [comment]
Documentation moved to https://github.com/dodona-edu/dodona-edu.github.io
