### ISSUE TITLE
Python Judge

### ISSUE THREAD

**Issue by mdnert** [dodona-edu/dodona-docs#4]
Ik heb twee .txt-bestanden toegevoegd in "workdirectory" . Het eerste (korte) bestand wordt goed gecontroleerd. Het tweede (langere) bestand geeft problemen. De verwachte uitvoer wordt wel gemaakt en getoond, maar als ik de oefening "volg", dan wordt het bestand niet gevonden:
![afbeelding](https://user-images.githubusercontent.com/42645963/44529678-f8b67580-a6ec-11e8-9a2a-a3e9286635fd.png)

**Comment by mdnert** [comment]
Ondertussen opgemerkt dat het voor geen enkele oplossing lukt om de ingediende code te volgen. Er komt altijd FileNotFoundError. De controle zelf gebeurt zonder fouten, maar het is dus niet mogelijk om de fouten op te sporen via Dodona

**Comment by ghost** [comment]
Om de files te kunnen gebruiken in de Python Tutor moet je de `FILE` tag gebruiken zoals [hier](https://dodona.readthedocs.io/nl/latest/pythia_judge.html#bestanden) beschreven en de bestanden in de `description/media` directory plaatsen. In jouw geval zal dit dus neerkomen op een extra lijn `<FILE name="woordlengte.txt" src="woordlengte.txt" href="media/woordlengte.txt" />` (als je `woordlengte.txt` rechtstreeks in `description/media` plaatst) voor het geval dat je in het screenshot toont.

Let ook dat de oefening publiek moet zijn voor dit zal werken (anders word de juiste inhoud van het bestand niet teruggegeven).

**Comment by mdnert** [comment]
Beste,

Bedankt voor het antwoord – ik had de uitleg over de FILE tag wel gelezen, maar het was me niet echt duidelijk wat de bedoeling was. De bestanden moeten dus zowel in workdirectory, als in media toegevoegd worden  of is daar nog een andere mogelijkheid?

Het is gelukt voor mijn oefeningen om de Pyton Tutor in orde te brengen, maar ik heb nog een probleem in 1 oefening.

In de Python Tutor is alles in orde, de return-waarde wordt correct bepaald, maar toch krijg ik een fout bij de feedback met een melding die ik niet begrijp:
[cid:image001.png@01D43BB5.9DB2FF20]

Kan je helpen ?

Mvg

M. Denert

**Comment by ghost** [comment]
De bestanden moeten inderdaad zowel in de `workdir` als in de `description/media` directories toegevoegd worden. De documentatie zal nog geupdatet worden om de impact op de Python Tutor van de `FILE` tags ook duidelijk te maken.

Om het andere probleem op te lossen moet je de evaluatie bestanden aanpassen. Het verwachte resultaat wordt als een Python value geïnterpreteerd, dus er moet `'Zowel het geloof als de wet houdt de moraal hoog. Alleen geeft het geloof de bovengrens van ons zedelijk leven aan, en de wet de ondergrens.'` staan in plaats van `Zowel het geloof als de wet houdt de moraal hoog. Alleen geeft het geloof de bovengrens van ons zedelijk leven aan, en de wet de ondergrens.`. (Het verschil zit in de aanhalingstekens).

P.S.: Als je dit soort mails via mail beantwoord wordt er automatisch een comment op Github aangemaakt, maar eventuele bijlages (zoals afbeeldingen) worden niet getoond.
