### ISSUE TITLE
exercise status with deadline

### ISSUE THREAD

**Issue by rien** [dodona-edu/dodona-docs#6]
The current explanation about the exercise status in the series card is not completely correct. It currently states

![image](https://user-images.githubusercontent.com/3226995/45369774-f6a64f00-b5e6-11e8-89d2-08219b9db387.png)

While the code responsible for this icon is currently the following:
```erb
<% if summary.solved_before_deadline? %>
  <i class="material-icons md-18 colored-correct">check</i>
<% elsif summary.solved? %>
  <i class="material-icons md-18 colored-wrong">check</i>
<% elsif summary.submitted? %>
  <i class="material-icons md-18 colored-wrong">close</i>
<% end %>
```
So the user gets to see a red cross if the last submission is incorrect **and** they do not have a correct submission before the deadline.

Because this could be confusing for users. Like I also posted in the `series-status` PR I suggest splitting this status into an exercise status (showing the correctness of the last submission) and a deadline status (showing whether the user solved the exercise before the deadline or not). This deadline status would only be shown after the deadline has passed, acting like a 'snapshot' taken at the instant the deadline passes.

![image](https://user-images.githubusercontent.com/3226995/45370237-17bb6f80-b5e8-11e8-93fa-56e2daca0fea.png)

**Comment by bmesuere** [comment]
Documentation moved to https://github.com/dodona-edu/dodona-edu.github.io
