### ISSUE TITLE
Pythia_judge_readfile

### ISSUE THREAD

**Issue by mdnert** [dodona-edu/dodona-docs#8]
I want to check if the output of a program is equal to the content of a file. How can I do this without copying the content of my file in 0.in - I use doctest.
It works fine with:
>>> lees("langerbestand.txt")   # doctest: 
<FILE name="langerbestand.txt" src="langerbestand.txt" href="media/langerbestand.txt" />
Dit bestand heeft twee lijnen.
Tweede lijn.

But I look for a solution where I can 'read' the content of the file, instead of copying it.

**Comment by ninewise** [comment]
@pdawyndt didn't we add files to the doctests recently?

**Comment by mdnert** [comment]
I can use files, but I want to check if the result of the student is the same as the content of a specific file - without copying the content of that file in  0.in

**Comment by dmouriss** [comment]
It is possible and it can be done with 
\< FILE href="" \>

For example:
```
>>> decode('cipher01.txt')
<FILE name="cipher01.txt" src="" href="media/cipher01.txt" />
'goldmakesmonstersofmen'
```
Just make sure the file is available in the media directory of the description.

**Comment by mdnert** [comment]
This is the code to pass a file to a method. Can you look at https://dodona.ugent.be/nl/exercises/1469049593/ . In the first tests I added the content to the file 0.in , in the second test I want to use the contect of a file - I tried:
>>> lees('bron.txt')   # doctest:
<FILE name="bron.txt" src="bron.txt" href="media/bron.txt" />
>>> print(open('bron.txt').read())  # doctest:
<FILE name="bron.txt" src="bron.txt" href="media/bron.txt" />

But the test does not succeed

**Comment by dmouriss** [comment]
Normally this is done by directly copy pasting the contents of the file in the testfile (or when you use a script to generate the testfiles, make the generator script write it to the testfile).

However when you want to avoid this, I think the only option is to write a custom outputprocessor. This is an example of a possible testfile for two testcases. One for the file 'abc.txt' and one for the file 'def.txt'

```
>>> lees('abc.txt') # doctest: +STDOUT

<DEFINITION>
class CompareWithFileProcessor(OutputProcessor):

    def __init__(self, sourcefile, **kwargs):
        super().__init__(**kwargs)
        self.sourcefile = sourcefile

    def checkStdout(self, expected, generated, **kwargs):
        filecontent = open(self.sourcefile, 'r').read()

        self.setOutput(
                    channel='stdout', 
                    expected=filecontent,
                    generated=generated,
                )
        return generated == filecontent
</DEFINITION>

<OUTPUTPROCESSOR>
CompareWithFileProcessor('abc.txt')
</OUTPUTPROCESSOR>

>>> lees('def.txt') # doctest: +STDOUT
<OUTPUTPROCESSOR>
CompareWithFileProcessor('abc.txt')
</OUTPUTPROCESSOR>
```
Make sure the files 'abc.txt' and 'def.txt' are in the workdir folder and the following solution should work:

````
def lees(bestandsnaam):
    print(open(bestandsnaam, 'r').read(), end = '')
```

**Comment by bmesuere** [comment]
Documentation moved to https://github.com/dodona-edu/dodona-edu.github.io
